"""Portable public-MCP scenarios for Agent Relay.

This module owns the action sequence shared by native platform harnesses. A
harness supplies only a generated loopback MCP URL, an ephemeral control token,
an expected device identity, and a temporary fixture directory. The scenario
never starts a process, constructs a Relay WebSocket frame, or accepts arbitrary
command/path input.
"""

from __future__ import annotations

import asyncio
import importlib.util
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Final

try:
    from tests.e2e import mcp_client as _mcp
    from tests.e2e import oracles as _oracles
except ModuleNotFoundError as error:
    if error.name not in {"tests", "tests.e2e"}:
        raise

    def _load_sibling(name: str):
        dotted = f"_agent_relay_e2e_{name}"
        cached = sys.modules.get(dotted)
        if cached is not None:
            return cached
        target = Path(__file__).with_name(f"{name}.py")
        spec = importlib.util.spec_from_file_location(dotted, target)
        if spec is None or spec.loader is None:
            raise ImportError(f"cannot load portable kernel module {name}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[dotted] = module
        spec.loader.exec_module(module)
        return module

    _mcp = _load_sibling("mcp_client")
    _oracles = _load_sibling("oracles")

EXPECTED_MCP_TOOLS: Final[tuple[str, ...]] = _mcp.EXPECTED_MCP_TOOLS
TOOL_ORDER: Final[tuple[str, ...]] = (
    "system.ping",
    "terminal.exec",
    "browser.list_tabs",
    "browser.navigate",
    "browser.read_page",
    "browser.fill",
    "browser.click",
    "computer.capture",
    "computer.click",
    "computer.type",
)
FIXTURE_TITLE: Final[str] = "Relay Browser Fixture"
EVENT_FILE: Final[str] = "browser-events.jsonl"
COMPUTER_EVENT_FILE: Final[str] = "computer-events.jsonl"
EVENT_POLL_TIMEOUT: Final[float] = 5.0
MCP_OPERATION_TIMEOUT: Final[float] = 10.0


@dataclass(frozen=True)
class RuntimeConfig:
    """Bounded, harness-built runtime inputs for a portable scenario.

    ``fixtures_root`` is generated by the harness and is used only with the
    two fixed event filenames declared above. It is not a caller-selected
    capability path or a path accepted by the Relay protocol.
    """

    mcp_url: str
    control_token: str
    device_id: str
    run_id: str
    fixture_url: str
    fixtures_root: str


def _mark(phase: list[str] | None, value: str) -> None:
    if phase is not None:
        phase[:] = [value]


def _fixture_path(runtime: RuntimeConfig, filename: str) -> Path:
    return Path(runtime.fixtures_root) / filename


def _portable_phase(
    phase: list[str] | None,
    markers: list[str],
    fallback: str,
) -> None:
    """Map detailed oracle markers to the closed harness phase vocabulary."""
    if phase is None:
        return
    marker = markers[-1] if markers else fallback
    if marker.startswith("read-page-element-"):
        marker = "read-page-element-schema"
    elif marker.startswith("capture-element-"):
        marker = "capture-element-shape"
    elif marker in {"capture-duplicate-id", "capture-decoy-detected"}:
        marker = "capture-duplicate" if marker == "capture-duplicate-id" else "capture-decoy"
    elif marker in {"capture-count-out-of-range", "capture-identity-mismatch"}:
        marker = "capture-count" if marker == "capture-count-out-of-range" else "capture-identity"
    elif marker == "capture-top-level-mismatch":
        marker = "capture-top-level"
    elif marker in {
        "capture-controls-field-mismatch",
        "capture-controls-button-mismatch",
    }:
        marker = "capture-controls"
    elif marker == "read-page-success":
        marker = "read-page-controls"
    _mark(phase, marker)


def _diagnose_pwd_mismatch(result: object, expected: str) -> None:
    """Log bounded path-shape facts without exposing the workspace path."""
    payload = getattr(result, "structuredContent", None)
    actual = payload.get("stdout") if isinstance(payload, dict) else None
    if not isinstance(actual, str):
        print("Native E2E pwd diagnostic: stdout unavailable.", file=sys.stderr)
        return
    normalized_actual = actual.replace("\\", "/")
    expected_output = expected + "\n"
    normalized_expected = expected_output.replace("\\", "/")
    print(
        "Native E2E pwd diagnostic: "
        f"actual_len={len(actual)} expected_len={len(expected_output)} "
        f"exact={actual == expected_output} "
        f"casefold={actual.casefold() == expected_output.casefold()} "
        f"slash_normalized={normalized_actual == normalized_expected} "
        f"trailing_newline={actual.endswith(chr(10))}.",
        file=sys.stderr,
    )


async def _run_core_scenario_async(
    runtime: RuntimeConfig,
    phase: list[str] | None = None,
    expected_capabilities: tuple[str, ...] | None = None,
    expected_pwd: str = "/workspace",
) -> None:
    """Run tools/list, status, ping, and fixed terminal markers."""
    async with _mcp.MCPClientSession(
        runtime.mcp_url,
        runtime.control_token,
    ) as client:
        _mark(phase, "tools-list")
        if await client.list_tools() != EXPECTED_MCP_TOOLS:
            raise ValueError("unexpected MCP tools")
        _mark(phase, "device-status")
        _oracles.validate_status(
            await client.call("relay_device_status", {}),
            device_id=runtime.device_id,
            connected=True,
            expected_capabilities=expected_capabilities,
        )
        _mark(phase, "system-ping")
        _oracles.validate_ping(await client.call("relay_system_ping", {}))
        for command_id, expected in (
            ("pwd", expected_pwd),
            ("git_branch", "relay-e2e-marker"),
        ):
            _mark(phase, f"terminal-{command_id.replace('_', '-')}")
            result = await client.call(
                "relay_terminal_exec", {"command_id": command_id}
            )
            try:
                _oracles.validate_terminal(
                    result,
                    command_id=command_id,
                    expected=expected,
                )
            except ValueError:
                if command_id == "pwd":
                    _diagnose_pwd_mismatch(result, expected)
                raise


def run_core_scenario(
    runtime: RuntimeConfig,
    phase: list[str] | None = None,
    *,
    expected_capabilities: tuple[str, ...] | None = None,
    expected_pwd: str = "/workspace",
) -> None:
    """Synchronous wrapper for the portable core scenario."""
    asyncio.run(
        asyncio.wait_for(
            _run_core_scenario_async(
                runtime,
                phase,
                expected_capabilities,
                expected_pwd,
            ),
            timeout=MCP_OPERATION_TIMEOUT * 4,
        )
    )


async def _run_browser_scenario_async(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    expected_capabilities: tuple[str, ...] | None = None,
) -> None:
    """Exercise Browser Use through one official MCP session and one oracle."""
    artifact = _fixture_path(runtime, EVENT_FILE)
    async with _mcp.MCPClientSession(
        runtime.mcp_url,
        runtime.control_token,
    ) as client:
        _mark(phase, "tools-list")
        if await client.list_tools() != EXPECTED_MCP_TOOLS:
            raise ValueError("unexpected MCP tools")
        _mark(phase, "device-status")
        _oracles.validate_status(
            await client.call("relay_device_status", {}),
            device_id=runtime.device_id,
            connected=True,
            expected_capabilities=expected_capabilities,
        )
        _mark(phase, "list-tabs")
        tab_id = _oracles.validate_list_tabs(
            await client.call("relay_browser_list_tabs", {})
        )
        _mark(phase, "navigate")
        _oracles.validate_action(
            await client.call("relay_browser_navigate", {"url": runtime.fixture_url}),
            tool_name="relay_browser_navigate",
            tab_id=tab_id,
            element_id=None,
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "read-page-call")
        result = await client.call("relay_browser_read_page", {})
        markers: list[str] = []
        try:
            textbox, button = _oracles.validate_read_page(
                result,
                tab_id=tab_id,
                fixture_url=runtime.fixture_url,
                fixture_title=FIXTURE_TITLE,
                diagnostic_phase=markers,
            )
        except ValueError:
            _portable_phase(phase, markers, "read-page-validation")
            raise
        _mark(phase, "disallowed-origin")
        forbidden_url = "https://example.invalid/"
        rejected_origin = await client.call(
            "relay_browser_navigate",
            {"url": forbidden_url},
        )
        if rejected_origin.isError is not True or forbidden_url in str(rejected_origin):
            raise ValueError("disallowed Browser origin was not safely rejected")
        _mark(phase, "stale-element")
        _oracles.validate_action(
            await client.call("relay_browser_navigate", {"url": runtime.fixture_url}),
            tool_name="relay_browser_navigate",
            tab_id=tab_id,
            element_id=None,
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        stale = await client.call(
            "relay_browser_fill",
            {"element_id": textbox, "value": value},
        )
        if stale.isError is not True or textbox in str(stale):
            raise ValueError("stale Browser element was not safely rejected")
        _mark(phase, "refresh-page")
        refreshed = _oracles.validate_read_page(
            await client.call("relay_browser_read_page", {}),
            tab_id=tab_id,
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        textbox, button = refreshed
        _mark(phase, "fill")
        _oracles.validate_action(
            await client.call(
                "relay_browser_fill",
                {"element_id": textbox, "value": value},
            ),
            tool_name="relay_browser_fill",
            tab_id=tab_id,
            element_id=textbox,
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "pre-click-oracle")
        _oracles.assert_no_fixture_event(artifact)
        _mark(phase, "click")
        _oracles.validate_action(
            await client.call("relay_browser_click", {"element_id": button}),
            tool_name="relay_browser_click",
            tab_id=tab_id,
            element_id=button,
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
    _mark(phase, "artifact-event")
    _oracles.poll_fixture_event(
        artifact,
        run_id=runtime.run_id,
        value=value,
        timeout=EVENT_POLL_TIMEOUT,
    )


def run_browser_scenario(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    *,
    expected_capabilities: tuple[str, ...] | None = None,
) -> None:
    """Run the shared Browser Use scenario with bounded cleanup."""
    asyncio.run(
        asyncio.wait_for(
            _run_browser_scenario_async(
                runtime,
                value,
                phase,
                expected_capabilities,
            ),
            timeout=MCP_OPERATION_TIMEOUT * 6,
        )
    )


async def _run_computer_scenario_async(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    expected_capabilities: tuple[str, ...] | None = None,
) -> None:
    """Exercise bounded Computer Use controls and the stale-element rejection."""
    artifact = _fixture_path(runtime, COMPUTER_EVENT_FILE)
    async with _mcp.MCPClientSession(
        runtime.mcp_url,
        runtime.control_token,
    ) as client:
        _mark(phase, "device-status")
        _oracles.validate_status(
            await client.call("relay_device_status", {}),
            device_id=runtime.device_id,
            connected=True,
            expected_capabilities=expected_capabilities,
        )
        _mark(phase, "capture")
        first = await client.call("relay_computer_capture", {})
        markers: list[str] = []
        try:
            field, button = _oracles.validate_computer_capture(
                first,
                diagnostic_phase=markers,
            )
        except ValueError:
            _portable_phase(phase, markers, "capture-controls")
            raise
        first_payload = first.structuredContent
        assert isinstance(first_payload, dict)
        generation = first_payload["generation"]
        _mark(phase, "click-field")
        _oracles.validate_computer_action(
            await client.call("relay_computer_click", {"element_id": field}),
            tool_name="relay_computer_click",
            generation=generation,
            element_id=field,
        )
        _mark(phase, "type-field")
        _oracles.validate_computer_action(
            await client.call(
                "relay_computer_type",
                {"element_id": field, "text": value},
            ),
            tool_name="relay_computer_type",
            generation=generation,
            element_id=field,
        )
        _mark(phase, "recapture")
        second = await client.call("relay_computer_capture", {})
        second_markers: list[str] = []
        try:
            fresh_field, fresh_button = _oracles.validate_computer_capture(
                second,
                diagnostic_phase=second_markers,
            )
        except ValueError:
            _portable_phase(phase, second_markers, "capture-controls")
            raise
        second_payload = second.structuredContent
        assert isinstance(second_payload, dict)
        fresh_generation = second_payload["generation"]
        if fresh_generation == generation or fresh_field == field:
            raise ValueError("computer capture generation was not refreshed")
        _mark(phase, "stale-click")
        stale = await client.call("relay_computer_click", {"element_id": button})
        if stale.isError is not True or button in str(stale):
            raise ValueError("stale computer element was not safely rejected")
        _mark(phase, "stale-click-oracle")
        _oracles.assert_no_fixture_event(artifact)
        _mark(phase, "click-button")
        _oracles.validate_computer_action(
            await client.call(
                "relay_computer_click",
                {"element_id": fresh_button},
            ),
            tool_name="relay_computer_click",
            generation=fresh_generation,
            element_id=fresh_button,
        )
    _mark(phase, "artifact-event")
    deadline = time.monotonic() + EVENT_POLL_TIMEOUT
    previous: bytes | None = None
    while time.monotonic() < deadline:
        try:
            current = _oracles.validate_computer_event(
                artifact,
                run_id=runtime.run_id,
                value=value,
            )
        except ValueError:
            time.sleep(0.05)
            continue
        if current == previous:
            _mark(phase, "stable-event")
            return
        previous = current
        time.sleep(0.1)
    _oracles.validate_computer_event(
        artifact,
        run_id=runtime.run_id,
        value=value,
    )


def run_computer_scenario(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    *,
    expected_capabilities: tuple[str, ...] | None = None,
) -> None:
    """Run the shared Computer Use scenario with bounded cleanup."""
    asyncio.run(
        asyncio.wait_for(
            _run_computer_scenario_async(
                runtime,
                value,
                phase,
                expected_capabilities,
            ),
            timeout=MCP_OPERATION_TIMEOUT * 8,
        )
    )
