"""Portable public-MCP scenarios for Agent Relay.

This module owns the action sequence shared by native platform harnesses. A
harness supplies only a generated loopback MCP URL, an ephemeral control token,
an expected device identity, and a temporary fixture directory. The scenario
never starts a process, constructs a Relay WebSocket frame, or accepts arbitrary
command/path input.
"""

from __future__ import annotations

import asyncio
import hashlib
import importlib.util
import sys
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Final

try:
    from tests.e2e import mcp_client as _mcp
    from tests.e2e import oracles as _oracles
except ModuleNotFoundError as error:
    if error.name not in {"tests", "tests.e2e"}:
        raise

    def _load_sibling(name: str):
        dotted = f"_agent_relay_e2e_{name}"
        cached = sys.modules.get(dotted)
        if cached is not None:
            return cached
        target = Path(__file__).with_name(f"{name}.py")
        spec = importlib.util.spec_from_file_location(dotted, target)
        if spec is None or spec.loader is None:
            raise ImportError(f"cannot load portable kernel module {name}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[dotted] = module
        spec.loader.exec_module(module)
        return module

    _mcp = _load_sibling("mcp_client")
    _oracles = _load_sibling("oracles")

EXPECTED_MCP_TOOLS: Final[tuple[str, ...]] = _mcp.EXPECTED_MCP_TOOLS
MCP_OPERATION_TIMEOUT: Final[float] = 10.0
MCP_BROWSER_HTTP_TIMEOUT: Final[float] = 30.0
EVENT_POLL_TIMEOUT: Final[float] = 10.0
CUA_EVENT_FILE: Final[str] = "computer-events.jsonl"
CORE_MCP_TOOLS: Final[tuple[str, ...]] = (
    "relay_device_status",
    "relay_system_ping",
    "relay_terminal_exec",
)
CUA_MCP_TOOLS: Final[tuple[str, ...]] = CORE_MCP_TOOLS + (
    "relay_cua_list_windows",
    "relay_cua_get_window_state",
    "relay_cua_launch_app",
    "relay_cua_kill_app",
    "relay_cua_click",
    "relay_cua_type_text",
    "relay_cua_get_browser_state",
    "relay_cua_browser_prepare",
    "relay_cua_browser_navigate",
    "relay_cua_browser_click",
    "relay_cua_browser_type",
    "relay_cua_start_session",
    "relay_cua_end_session",
)
CUA_DESKTOP_MCP_TOOLS: Final[tuple[str, ...]] = CORE_MCP_TOOLS + (
    "relay_cua_list_windows",
    "relay_cua_get_window_state",
    "relay_cua_click",
    "relay_cua_type_text",
)
CUA_BROWSER_SESSION_PREFIX: Final[str] = "relay-cua-browser-"


@dataclass(frozen=True)
class RuntimeConfig:
    """Bounded, harness-built runtime inputs for a portable scenario.

    ``fixtures_root`` is generated by the harness and is used only with the
    two fixed event filenames declared above. ``fixture_url`` is the optional
    loopback page served by the same CUA harness for its integrated browser
    sub-scenario. Neither value is a caller-selected capability path or a path
    accepted by the Relay protocol.
    """

    mcp_url: str
    control_token: str
    device_id: str
    run_id: str
    fixture_url: str
    fixtures_root: str
    browser_pid: str = ""


def _mark(phase: list[str] | None, value: str) -> None:
    if phase is not None:
        phase[:] = [value]


def _fixture_path(runtime: RuntimeConfig, filename: str) -> Path:
    return Path(runtime.fixtures_root) / filename


def _require_tools(discovered: tuple[str, ...], required: tuple[str, ...]) -> None:
    """Ensure the scenario received exactly its announced tool contract."""
    if discovered != required:
        raise ValueError("unexpected MCP tools")


def _portable_phase(
    phase: list[str] | None,
    markers: list[str],
    fallback: str,
) -> None:
    """Map detailed oracle markers to the closed harness phase vocabulary."""
    if phase is None:
        return
    marker = markers[-1] if markers else fallback
    if marker.startswith("snapshot-element-"):
        marker = "snapshot-element-schema"
    elif marker.startswith("capture-element-"):
        marker = "capture-element-shape"
    elif marker in {"capture-duplicate-id", "capture-decoy-detected"}:
        marker = "capture-duplicate" if marker == "capture-duplicate-id" else "capture-decoy"
    elif marker in {"capture-count-out-of-range", "capture-identity-mismatch"}:
        marker = "capture-count" if marker == "capture-count-out-of-range" else "capture-identity"
    elif marker == "capture-top-level-mismatch":
        marker = "capture-top-level"
    elif marker in {
        "capture-controls-field-mismatch",
        "capture-controls-button-mismatch",
    }:
        marker = "capture-controls"
    elif marker == "snapshot-success":
        marker = "snapshot-controls"
    _mark(phase, marker)


def _diagnose_pwd_mismatch(result: object, expected: str) -> None:
    """Log bounded path-shape facts without exposing the workspace path."""
    payload = getattr(result, "structuredContent", None)
    actual = payload.get("stdout") if isinstance(payload, dict) else None
    if not isinstance(actual, str):
        print("E2E pwd diagnostic: stdout unavailable.", file=sys.stderr)
        return
    normalized_actual = actual.replace("\\", "/")
    expected_output = expected + "\n"
    normalized_expected = expected_output.replace("\\", "/")
    print(
        "E2E pwd diagnostic: "
        f"actual_len={len(actual)} expected_len={len(expected_output)} "
        f"exact={actual == expected_output} "
        f"casefold={actual.casefold() == expected_output.casefold()} "
        f"slash_normalized={normalized_actual == normalized_expected} "
        f"trailing_newline={actual.endswith(chr(10))}.",
        file=sys.stderr,
    )


def _diagnose_browser_prepare(result: object) -> None:
    """Log bounded facts for a rejected browser prepare result."""
    known_refusal_codes = {
        "browser_action_unavailable",
        "browser_binding_ambiguous",
        "browser_binding_stale",
        "browser_consent_required",
        "browser_consent_revoked",
        "browser_endpoint_owner_mismatch",
        "browser_input_incomplete",
        "browser_input_trust_unavailable",
        "browser_origin_outside_scope",
        "browser_reconnect_exhausted",
        "browser_ref_stale",
        "browser_requires_setup",
        "browser_route_unavailable",
        "browser_tab_not_found",
        "browser_tab_required",
        "browser_wrong_target_refused",
    }
    content = getattr(result, "content", None)
    content_items = content if isinstance(content, list) else []
    content_types = sorted(
        {
            value
            for item in content_items
            if isinstance(value := getattr(item, "type", None), str)
        }
    )
    text_lengths: list[int] = []
    text_digests: list[str] = []
    text_keywords: set[str] = set()
    content_codes: set[str] = set()
    keywords = (
        "browser",
        "consent",
        "profile",
        "setup",
        "window",
        "endpoint",
        "target",
        "timeout",
        "denied",
        "rejected",
    )
    for item in content_items:
        text = getattr(item, "text", None)
        if not isinstance(text, str):
            continue
        text_lengths.append(len(text))
        text_digests.append(hashlib.sha256(text.encode("utf-8")).hexdigest()[:16])
        normalized = text.casefold().replace("-", "_").replace(" ", "_")
        text_keywords.update(keyword for keyword in keywords if keyword in normalized)
        content_codes.update(code for code in known_refusal_codes if code in normalized)
    content_facts = (
        f"content_count={len(content_items)} "
        f"content_types={','.join(content_types) or 'none'} "
        f"text_lengths={','.join(map(str, text_lengths)) or 'none'} "
        f"text_digests={','.join(text_digests) or 'none'} "
        f"text_keywords={','.join(sorted(text_keywords)) or 'none'} "
        f"content_codes={','.join(sorted(content_codes)) or 'none'}"
    )
    payload = getattr(result, "structuredContent", None)
    if not isinstance(payload, dict):
        print(
            "E2E browser prepare diagnostic: "
            f"structured_content=unavailable {content_facts}.",
            file=sys.stderr,
        )
        return
    status = payload.get("status")
    prepared = payload.get("prepared")
    prepared_pid = payload.get("prepared_pid")
    refusal = payload.get("refusal")
    refusal_code = refusal.get("code") if isinstance(refusal, dict) else None
    refusal_keys = (
        ",".join(sorted(refusal))
        if isinstance(refusal, dict)
        else "none"
    )
    refusal_detail = refusal.get("detail") if isinstance(refusal, dict) else None
    refusal_detail_keys = (
        ",".join(sorted(refusal_detail))
        if isinstance(refusal_detail, dict)
        else "none"
    )
    print(
        "E2E browser prepare diagnostic: "
        f"field_count={len(payload)} "
        f"status_ok={status == 'ok'} status_type={type(status).__name__} "
        f"status_refused={status == 'refused'} status_error={status == 'error'} "
        f"has_refusal={'refusal' in payload} has_error={'error' in payload} "
        f"has_message={'message' in payload} has_code={'code' in payload} "
        f"prepared_true={prepared is True} prepared_type={type(prepared).__name__} "
        f"pid_positive={type(prepared_pid) is int and prepared_pid > 0} "
        f"pid_type={type(prepared_pid).__name__} "
        f"refusal_code={refusal_code if refusal_code in known_refusal_codes else 'other'} "
        f"refusal_keys={refusal_keys} refusal_detail_keys={refusal_detail_keys} "
        f"{content_facts}.",
        file=sys.stderr,
    )


async def _run_core_scenario_async(
    runtime: RuntimeConfig,
    phase: list[str] | None = None,
    expected_capabilities: tuple[str, ...] | None = None,
    expected_pwd: str = "/workspace",
) -> None:
    """Run tools/list, status, ping, and fixed terminal markers."""
    async with _mcp.MCPClientSession(
        runtime.mcp_url,
        runtime.control_token,
    ) as client:
        _mark(phase, "tools-list")
        _require_tools(await client.list_tools(), CORE_MCP_TOOLS)
        _mark(phase, "device-status")
        _oracles.validate_status(
            await client.call("relay_device_status", {}),
            device_id=runtime.device_id,
            connected=True,
            expected_capabilities=expected_capabilities,
        )
        _mark(phase, "system-ping")
        _oracles.validate_ping(await client.call("relay_system_ping", {}))
        for command_id, expected in (
            ("pwd", expected_pwd),
            ("git_branch", "relay-e2e-marker"),
        ):
            _mark(phase, f"terminal-{command_id.replace('_', '-')}")
            result = await client.call(
                "relay_terminal_exec", {"command_id": command_id}
            )
            try:
                _oracles.validate_terminal(
                    result,
                    command_id=command_id,
                    expected=expected,
                )
            except ValueError:
                if command_id == "pwd":
                    _diagnose_pwd_mismatch(result, expected)
                raise


async def _run_cua_browser_subscenario(
    client: _mcp.MCPClientSession,
    runtime: RuntimeConfig,
    phase: list[str] | None,
) -> None:
    """Exercise the CUA browser contract in a dedicated browser process."""
    if not runtime.fixture_url.startswith("http://127.0.0.1:"):
        raise ValueError("CUA browser fixture must be loopback HTTP")
    session = f"{CUA_BROWSER_SESSION_PREFIX}{runtime.run_id}"
    initial_pid: int | None = None
    prepared_pid: int | None = None
    session_started = False
    launch_profile_dir: tempfile.TemporaryDirectory[str] | None = None
    primary_error: BaseException | None = None
    primary_phase: str | None = None
    try:
        if runtime.browser_pid:
            if not runtime.browser_pid.isascii() or not runtime.browser_pid.isdecimal():
                raise ValueError("invalid CUA browser fixture process")
            initial_pid = int(runtime.browser_pid)
            if initial_pid <= 0:
                raise ValueError("CUA browser fixture process is unavailable")
        else:
            _mark(phase, "browser-launch")
            launch_profile_dir = tempfile.TemporaryDirectory(
                prefix="agent-relay-cua-browser-"
            )
            launch_profile = Path(launch_profile_dir.name)
            initial_pid = _oracles.validate_cua_browser_launch(
                await client.call(
                    "relay_cua_launch_app",
                    {
                        "name": "chromium",
                        "additional_arguments": [
                            f"--user-data-dir={launch_profile}",
                            "--no-first-run",
                            "--no-default-browser-check",
                            "--disable-background-networking",
                            "--disable-component-update",
                            "--disable-extensions",
                            "--disable-default-apps",
                            "--new-window",
                            "--no-sandbox",
                            "--disable-dev-shm-usage",
                            "--disable-gpu",
                            "--force-renderer-accessibility",
                            runtime.fixture_url,
                        ],
                    },
                )
            )
        _mark(phase, "browser-session-start")
        _oracles.validate_cua_browser_success(
            await client.call(
                "relay_cua_start_session",
                {"session": session, "capture_scope": "window"},
            ),
            tool_name="relay_cua_start_session",
        )
        session_started = True
        _mark(phase, "browser-window-anchor")
        prepare_pid = initial_pid
        if runtime.browser_pid:
            if not runtime.browser_pid.isascii() or not runtime.browser_pid.isdecimal():
                raise ValueError("invalid CUA browser fixture process")
            prepare_pid = int(runtime.browser_pid)
        if type(prepare_pid) is not int or prepare_pid <= 0:
            raise ValueError("CUA browser fixture process is unavailable")
        _anchor_pid, browser_window_id = _oracles.validate_cua_list_windows(
            await client.call(
                "relay_cua_list_windows",
                {"pid": prepare_pid},
            ),
            expected_pid=prepare_pid,
        )
        _mark(phase, "browser-prepare")
        prepare_result = await client.call(
            "relay_cua_browser_prepare",
            {
                "pid": prepare_pid,
                "window_id": browser_window_id,
                "session": session,
                "strategy": {"kind": "existing_profile"},
            },
        )
        _mark(
            phase,
            "browser-prepare-provider-error"
            if getattr(prepare_result, "isError", None) is True
            else "browser-prepare-response",
        )
        try:
            prepared_pid = _oracles.validate_cua_browser_prepare(prepare_result)
        except ValueError:
            _diagnose_browser_prepare(prepare_result)
            raise
        _mark(phase, "browser-window")
        _prepared_pid, window_id = _oracles.validate_cua_list_windows(
            await client.call(
                "relay_cua_list_windows",
                {"pid": prepared_pid},
            ),
            expected_pid=prepared_pid,
        )
        _mark(phase, "browser-bind")
        target_id, tab_id = _oracles.validate_cua_browser_binding(
            await client.call(
                "relay_cua_get_browser_state",
                {
                    "pid": prepared_pid,
                    "window_id": window_id,
                    "session": session,
                },
            ),
            expected_pid=prepared_pid,
            expected_window_id=window_id,
        )
        _mark(phase, "browser-navigate")
        _oracles.validate_cua_browser_success(
            await client.call(
                "relay_cua_browser_navigate",
                {
                    "target_id": target_id,
                    "tab_id": tab_id,
                    "session": session,
                    "url": runtime.fixture_url,
                },
            ),
            tool_name="relay_cua_browser_navigate",
        )
        _mark(phase, "browser-state")
        browser_state = await client.call(
            "relay_cua_get_browser_state",
            {
                "target_id": target_id,
                "tab_id": tab_id,
                "session": session,
            },
        )
        _oracles.validate_cua_browser_state(
            browser_state,
            expected_url=runtime.fixture_url,
        )
        field_ref, button_ref = _oracles.validate_cua_browser_controls(
            browser_state,
            expected_url=runtime.fixture_url,
        )
        browser_value = "b-value"
        _mark(phase, "browser-type")
        _oracles.validate_cua_browser_success(
            await client.call(
                "relay_cua_browser_type",
                {
                    "target_id": target_id,
                    "tab_id": tab_id,
                    "ref": field_ref,
                    "text": browser_value,
                    "replace": True,
                    "session": session,
                },
            ),
            tool_name="relay_cua_browser_type",
        )
        _mark(phase, "browser-click")
        _oracles.validate_cua_browser_success(
            await client.call(
                "relay_cua_browser_click",
                {
                    "target_id": target_id,
                    "tab_id": tab_id,
                    "ref": button_ref,
                    "session": session,
                },
            ),
            tool_name="relay_cua_browser_click",
        )
        _mark(phase, "browser-state-after-click")
        _oracles.validate_cua_browser_state(
            await client.call(
                "relay_cua_get_browser_state",
                {
                    "target_id": target_id,
                    "tab_id": tab_id,
                    "session": session,
                },
            ),
            expected_url=runtime.fixture_url,
            expected_text="applied",
        )
        _mark(phase, "browser-event")
        _oracles.poll_cua_event(
            _fixture_path(runtime, CUA_EVENT_FILE),
            run_id=runtime.run_id,
            value=browser_value,
            timeout=EVENT_POLL_TIMEOUT,
        )
    except BaseException as error:
        primary_error = error
        if phase:
            primary_phase = phase[-1]
    finally:
        cleanup_error: BaseException | None = None
        if session_started:
            _mark(phase, "browser-session-end")
            try:
                _oracles.validate_cua_browser_success(
                    await client.call(
                        "relay_cua_end_session",
                        {"session": session},
                    ),
                    tool_name="relay_cua_end_session",
                )
            except BaseException as error:
                cleanup_error = error
        cleanup_pids: list[int] = []
        for candidate in (prepared_pid, initial_pid):
            if type(candidate) is int and candidate > 0 and candidate not in cleanup_pids:
                cleanup_pids.append(candidate)
        if runtime.browser_pid.isascii() and runtime.browser_pid.isdecimal():
            runtime_pid = int(runtime.browser_pid)
            if runtime_pid > 0 and runtime_pid not in cleanup_pids:
                cleanup_pids.append(runtime_pid)
        for pid in cleanup_pids:
            _mark(phase, "browser-kill")
            try:
                _oracles.validate_cua_browser_success(
                    await client.call("relay_cua_kill_app", {"pid": pid}),
                    tool_name="relay_cua_kill_app",
                )
            except BaseException as error:
                if cleanup_error is None:
                    cleanup_error = error
        if launch_profile_dir is not None:
            launch_profile_dir.cleanup()
        if primary_error is None and cleanup_error is not None:
            raise cleanup_error
    if primary_error is not None:
        if primary_phase is not None:
            _mark(phase, primary_phase)
        raise primary_error


def run_core_scenario(
    runtime: RuntimeConfig,
    phase: list[str] | None = None,
    *,
    expected_capabilities: tuple[str, ...] | None = None,
    expected_pwd: str = "/workspace",
) -> None:
    """Synchronous wrapper for the portable core scenario."""
    asyncio.run(
        asyncio.wait_for(
            _run_core_scenario_async(
                runtime,
                phase,
                expected_capabilities,
                expected_pwd,
            ),
            timeout=MCP_OPERATION_TIMEOUT * 4,
        )
    )


async def _run_cua_scenario_async(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    expected_capabilities: tuple[str, ...] | None = None,
    *,
    expected_cua_app: str,
    expected_cua_window_title: str,
    include_browser: bool = False,
) -> None:
    """Exercise generic CUA inventory, snapshot tokens, and safe actions."""
    artifact = _fixture_path(runtime, CUA_EVENT_FILE)
    client_options = {"http_timeout": MCP_BROWSER_HTTP_TIMEOUT} if include_browser else {}
    async with _mcp.MCPClientSession(
        runtime.mcp_url,
        runtime.control_token,
        **client_options,
    ) as client:
        _mark(phase, "tools-list")
        _require_tools(
            await client.list_tools(),
            CUA_MCP_TOOLS if include_browser else CUA_DESKTOP_MCP_TOOLS,
        )
        _mark(phase, "device-status")
        _oracles.validate_status(
            await client.call("relay_device_status", {}),
            device_id=runtime.device_id,
            connected=True,
            expected_capabilities=expected_capabilities,
        )
        _mark(phase, "list-windows")
        pid, window_id = _oracles.validate_cua_list_windows(
            await client.call("relay_cua_list_windows", {}),
            expected_app=expected_cua_app,
            expected_window_title=expected_cua_window_title,
        )
        _mark(phase, "snapshot")
        markers: list[str] = []
        try:
            first = await client.call(
                "relay_cua_get_window_state",
                {
                    "pid": pid,
                    "window_id": window_id,
                    "include_screenshot": False,
                    "max_elements": 128,
                },
            )
            first_snapshot, field_token, button_token = _oracles.validate_cua_window_state(
                first,
                expected_pid=pid,
                window_id=window_id,
                diagnostic_phase=markers,
            )
        except ValueError:
            _portable_phase(phase, markers, "cua-snapshot")
            raise
        _mark(phase, "click-field")
        _oracles.validate_cua_action(
            await client.call(
                "relay_cua_click",
                {"pid": pid, "window_id": window_id, "element_token": field_token},
            ),
            tool_name="relay_cua_click",
        )
        _mark(phase, "type-field")
        _oracles.validate_cua_action(
            await client.call(
                "relay_cua_type_text",
                {
                    "pid": pid,
                    "window_id": window_id,
                    "element_token": field_token,
                    "text": value,
                },
            ),
            tool_name="relay_cua_type_text",
        )
        _mark(phase, "recapture")
        second = await client.call(
            "relay_cua_get_window_state",
            {
                "pid": pid,
                "window_id": window_id,
                "include_screenshot": False,
                "max_elements": 128,
            },
        )
        second_snapshot, _, fresh_button_token = _oracles.validate_cua_window_state(
            second,
            expected_pid=pid,
            window_id=window_id,
        )
        if second_snapshot == first_snapshot or fresh_button_token == button_token:
            raise ValueError("CUA snapshot token was not refreshed")
        _mark(phase, "stale-click")
        stale = await client.call(
            "relay_cua_click",
            {"pid": pid, "window_id": window_id, "element_token": button_token},
        )
        if stale.isError is not True or button_token in str(stale):
            raise ValueError("stale CUA element was not safely rejected")
        _mark(phase, "stale-click-oracle")
        _oracles.assert_no_cua_event(artifact)
        _mark(phase, "click-button")
        _oracles.validate_cua_action(
            await client.call(
                "relay_cua_click",
                {"pid": pid, "window_id": window_id, "element_token": fresh_button_token},
            ),
            tool_name="relay_cua_click",
        )
        if include_browser:
            await _run_cua_browser_subscenario(client, runtime, phase)
    _mark(phase, "artifact-event")
    expected_event_value = "b-value" if include_browser else value
    deadline = time.monotonic() + EVENT_POLL_TIMEOUT
    previous: bytes | None = None
    while time.monotonic() < deadline:
        try:
            current = _oracles.validate_cua_event(
                artifact,
                run_id=runtime.run_id,
                value=expected_event_value,
            )
        except ValueError:
            time.sleep(0.05)
            continue
        if current == previous:
            _mark(phase, "stable-event")
            return
        previous = current
        time.sleep(0.1)
    _oracles.validate_cua_event(
        artifact,
        run_id=runtime.run_id,
        value=expected_event_value,
    )


def run_cua_scenario(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    *,
    expected_capabilities: tuple[str, ...] | None = None,
    expected_cua_app: str,
    expected_cua_window_title: str,
    include_browser: bool = False,
) -> None:
    """Run the shared generic CUA scenario with bounded cleanup."""
    asyncio.run(
        asyncio.wait_for(
            _run_cua_scenario_async(
                runtime,
                value,
                phase,
                expected_capabilities,
                expected_cua_app=expected_cua_app,
                expected_cua_window_title=expected_cua_window_title,
                include_browser=include_browser,
            ),
            timeout=MCP_OPERATION_TIMEOUT * 8,
        )
    )
