"""Portable public-MCP scenarios for Agent Relay.

This module owns the action sequence shared by native platform harnesses. A
harness supplies only a generated loopback MCP URL, an ephemeral control token,
an expected device identity, and a temporary fixture directory. The scenario
never starts a process, constructs a Relay WebSocket frame, or accepts arbitrary
command/path input.
"""

from __future__ import annotations

import asyncio
import importlib.util
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Final

try:
    from tests.e2e import mcp_client as _mcp
    from tests.e2e import oracles as _oracles
except ModuleNotFoundError as error:
    if error.name not in {"tests", "tests.e2e"}:
        raise

    def _load_sibling(name: str):
        dotted = f"_agent_relay_e2e_{name}"
        cached = sys.modules.get(dotted)
        if cached is not None:
            return cached
        target = Path(__file__).with_name(f"{name}.py")
        spec = importlib.util.spec_from_file_location(dotted, target)
        if spec is None or spec.loader is None:
            raise ImportError(f"cannot load portable kernel module {name}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[dotted] = module
        spec.loader.exec_module(module)
        return module

    _mcp = _load_sibling("mcp_client")
    _oracles = _load_sibling("oracles")

EXPECTED_MCP_TOOLS: Final[tuple[str, ...]] = _mcp.EXPECTED_MCP_TOOLS
CORE_MCP_TOOLS: Final[tuple[str, ...]] = (
    "relay_device_status",
    "relay_system_ping",
    "relay_terminal_exec",
)
BROWSER_MCP_TOOLS: Final[tuple[str, ...]] = CORE_MCP_TOOLS + (
    "relay_browser_list_tabs",
    "relay_browser_navigate",
    "relay_browser_snapshot",
    "relay_browser_fill",
    "relay_browser_click",
    "relay_browser_scroll",
    "relay_browser_type",
    "relay_browser_back",
)
CUA_MCP_TOOLS: Final[tuple[str, ...]] = CORE_MCP_TOOLS + (
    "relay_cua_list_windows",
    "relay_cua_get_window_state",
    "relay_cua_click",
    "relay_cua_type_text",
)
TOOL_ORDER: Final[tuple[str, ...]] = (
    "system.ping",
    "terminal.exec",
    "browser.list_tabs",
    "browser.navigate",
    "browser.snapshot",
    "browser.fill",
    "browser.click",
    "browser.scroll",
    "browser.type",
    "browser.back",
    "cua.list_windows",
    "cua.get_window_state",
    "cua.click",
    "cua.type_text",
)
FIXTURE_TITLE: Final[str] = "Relay Browser Fixture"
EVENT_FILE: Final[str] = "browser-events.jsonl"
CUA_EVENT_FILE: Final[str] = "computer-events.jsonl"
EVENT_POLL_TIMEOUT: Final[float] = 5.0
MCP_OPERATION_TIMEOUT: Final[float] = 10.0


@dataclass(frozen=True)
class RuntimeConfig:
    """Bounded, harness-built runtime inputs for a portable scenario.

    ``fixtures_root`` is generated by the harness and is used only with the
    two fixed event filenames declared above. It is not a caller-selected
    capability path or a path accepted by the Relay protocol.
    """

    mcp_url: str
    control_token: str
    device_id: str
    run_id: str
    fixture_url: str
    fixtures_root: str


def _mark(phase: list[str] | None, value: str) -> None:
    if phase is not None:
        phase[:] = [value]


def _fixture_path(runtime: RuntimeConfig, filename: str) -> Path:
    return Path(runtime.fixtures_root) / filename


def _require_tools(discovered: tuple[str, ...], required: tuple[str, ...]) -> None:
    """Ensure the scenario received exactly its announced tool contract."""
    if discovered != required:
        raise ValueError("unexpected MCP tools")


def _portable_phase(
    phase: list[str] | None,
    markers: list[str],
    fallback: str,
) -> None:
    """Map detailed oracle markers to the closed harness phase vocabulary."""
    if phase is None:
        return
    marker = markers[-1] if markers else fallback
    if marker.startswith("snapshot-element-"):
        marker = "snapshot-element-schema"
    elif marker.startswith("capture-element-"):
        marker = "capture-element-shape"
    elif marker in {"capture-duplicate-id", "capture-decoy-detected"}:
        marker = "capture-duplicate" if marker == "capture-duplicate-id" else "capture-decoy"
    elif marker in {"capture-count-out-of-range", "capture-identity-mismatch"}:
        marker = "capture-count" if marker == "capture-count-out-of-range" else "capture-identity"
    elif marker == "capture-top-level-mismatch":
        marker = "capture-top-level"
    elif marker in {
        "capture-controls-field-mismatch",
        "capture-controls-button-mismatch",
    }:
        marker = "capture-controls"
    elif marker == "snapshot-success":
        marker = "snapshot-controls"
    _mark(phase, marker)


def _diagnose_pwd_mismatch(result: object, expected: str) -> None:
    """Log bounded path-shape facts without exposing the workspace path."""
    payload = getattr(result, "structuredContent", None)
    actual = payload.get("stdout") if isinstance(payload, dict) else None
    if not isinstance(actual, str):
        print("E2E pwd diagnostic: stdout unavailable.", file=sys.stderr)
        return
    normalized_actual = actual.replace("\\", "/")
    expected_output = expected + "\n"
    normalized_expected = expected_output.replace("\\", "/")
    print(
        "E2E pwd diagnostic: "
        f"actual_len={len(actual)} expected_len={len(expected_output)} "
        f"exact={actual == expected_output} "
        f"casefold={actual.casefold() == expected_output.casefold()} "
        f"slash_normalized={normalized_actual == normalized_expected} "
        f"trailing_newline={actual.endswith(chr(10))}.",
        file=sys.stderr,
    )


async def _run_core_scenario_async(
    runtime: RuntimeConfig,
    phase: list[str] | None = None,
    expected_capabilities: tuple[str, ...] | None = None,
    expected_pwd: str = "/workspace",
) -> None:
    """Run tools/list, status, ping, and fixed terminal markers."""
    async with _mcp.MCPClientSession(
        runtime.mcp_url,
        runtime.control_token,
    ) as client:
        _mark(phase, "tools-list")
        _require_tools(await client.list_tools(), CORE_MCP_TOOLS)
        _mark(phase, "device-status")
        _oracles.validate_status(
            await client.call("relay_device_status", {}),
            device_id=runtime.device_id,
            connected=True,
            expected_capabilities=expected_capabilities,
        )
        _mark(phase, "system-ping")
        _oracles.validate_ping(await client.call("relay_system_ping", {}))
        for command_id, expected in (
            ("pwd", expected_pwd),
            ("git_branch", "relay-e2e-marker"),
        ):
            _mark(phase, f"terminal-{command_id.replace('_', '-')}")
            result = await client.call(
                "relay_terminal_exec", {"command_id": command_id}
            )
            try:
                _oracles.validate_terminal(
                    result,
                    command_id=command_id,
                    expected=expected,
                )
            except ValueError:
                if command_id == "pwd":
                    _diagnose_pwd_mismatch(result, expected)
                raise


def run_core_scenario(
    runtime: RuntimeConfig,
    phase: list[str] | None = None,
    *,
    expected_capabilities: tuple[str, ...] | None = None,
    expected_pwd: str = "/workspace",
) -> None:
    """Synchronous wrapper for the portable core scenario."""
    asyncio.run(
        asyncio.wait_for(
            _run_core_scenario_async(
                runtime,
                phase,
                expected_capabilities,
                expected_pwd,
            ),
            timeout=MCP_OPERATION_TIMEOUT * 4,
        )
    )


async def _run_browser_scenario_async(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    expected_capabilities: tuple[str, ...] | None = None,
) -> None:
    """Exercise Browser Use with structured locators and bounded snapshots."""
    artifact = _fixture_path(runtime, EVENT_FILE)
    secondary_url = runtime.fixture_url.rstrip("/") + "/second"
    async with _mcp.MCPClientSession(
        runtime.mcp_url,
        runtime.control_token,
    ) as client:
        _mark(phase, "tools-list")
        _require_tools(await client.list_tools(), BROWSER_MCP_TOOLS)
        _mark(phase, "device-status")
        _oracles.validate_status(
            await client.call("relay_device_status", {}),
            device_id=runtime.device_id,
            connected=True,
            expected_capabilities=expected_capabilities,
        )
        _mark(phase, "list-tabs")
        _oracles.validate_list_tabs(await client.call("relay_browser_list_tabs", {}))
        _mark(phase, "navigate")
        _oracles.validate_browser_action(
            await client.call("relay_browser_navigate", {"url": runtime.fixture_url}),
            tool_name="relay_browser_navigate",
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "snapshot")
        markers: list[str] = []
        try:
            textbox, button = _oracles.validate_snapshot(
                await client.call("relay_browser_snapshot", {}),
                fixture_url=runtime.fixture_url,
                fixture_title=FIXTURE_TITLE,
                diagnostic_phase=markers,
            )
        except ValueError:
            _portable_phase(phase, markers, "snapshot-validation")
            raise
        _mark(phase, "disallowed-origin")
        forbidden_url = "https://example.invalid/"
        rejected_origin = await client.call(
            "relay_browser_navigate",
            {"url": forbidden_url},
        )
        if rejected_origin.isError is not True or forbidden_url in str(rejected_origin):
            raise ValueError("disallowed Browser origin was not safely rejected")
        _mark(phase, "locator-refresh")
        # A locator is a bounded public query, not a provider handle. Re-resolve
        # it after navigation rather than replaying a stale opaque identifier.
        moved = await client.call("relay_browser_navigate", {"url": secondary_url})
        if moved.isError is not False:
            raise ValueError("secondary Browser navigation failed")
        returned = await client.call("relay_browser_back", {})
        _oracles.validate_browser_action(
            returned,
            tool_name="relay_browser_back",
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "refresh-snapshot")
        textbox, button = _oracles.validate_snapshot(
            await client.call("relay_browser_snapshot", {}),
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "type")
        _oracles.validate_browser_action(
            await client.call(
                "relay_browser_type",
                {"locator": textbox, "text": value},
            ),
            tool_name="relay_browser_type",
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "fill")
        _oracles.validate_browser_action(
            await client.call(
                "relay_browser_fill",
                {"locator": textbox, "value": value},
            ),
            tool_name="relay_browser_fill",
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "scroll-down")
        _oracles.validate_browser_action(
            await client.call("relay_browser_scroll", {"direction": "down"}),
            tool_name="relay_browser_scroll",
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "scroll-up")
        _oracles.validate_browser_action(
            await client.call("relay_browser_scroll", {"direction": "up"}),
            tool_name="relay_browser_scroll",
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        textbox, button = _oracles.validate_snapshot(
            await client.call("relay_browser_snapshot", {}),
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
        _mark(phase, "pre-click-oracle")
        _oracles.assert_no_fixture_event(artifact)
        _mark(phase, "click")
        _oracles.validate_browser_action(
            await client.call("relay_browser_click", {"locator": button}),
            tool_name="relay_browser_click",
            fixture_url=runtime.fixture_url,
            fixture_title=FIXTURE_TITLE,
        )
    _mark(phase, "artifact-event")
    _oracles.poll_fixture_event(
        artifact,
        run_id=runtime.run_id,
        value=value,
        timeout=EVENT_POLL_TIMEOUT,
    )


def run_browser_scenario(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    *,
    expected_capabilities: tuple[str, ...] | None = None,
) -> None:
    """Run the shared Browser Use scenario with bounded cleanup."""
    asyncio.run(
        asyncio.wait_for(
            _run_browser_scenario_async(
                runtime,
                value,
                phase,
                expected_capabilities,
            ),
            timeout=MCP_OPERATION_TIMEOUT * 6,
        )
    )


async def _run_cua_scenario_async(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    expected_capabilities: tuple[str, ...] | None = None,
    *,
    expected_cua_app: str,
    expected_cua_window_title: str,
) -> None:
    """Exercise generic CUA inventory, snapshot tokens, and safe actions."""
    artifact = _fixture_path(runtime, CUA_EVENT_FILE)
    async with _mcp.MCPClientSession(
        runtime.mcp_url,
        runtime.control_token,
    ) as client:
        _mark(phase, "tools-list")
        _require_tools(await client.list_tools(), CUA_MCP_TOOLS)
        _mark(phase, "device-status")
        _oracles.validate_status(
            await client.call("relay_device_status", {}),
            device_id=runtime.device_id,
            connected=True,
            expected_capabilities=expected_capabilities,
        )
        _mark(phase, "list-windows")
        pid, window_id = _oracles.validate_cua_list_windows(
            await client.call("relay_cua_list_windows", {}),
            expected_app=expected_cua_app,
            expected_window_title=expected_cua_window_title,
        )
        _mark(phase, "snapshot")
        markers: list[str] = []
        try:
            first = await client.call(
                "relay_cua_get_window_state",
                {
                    "pid": pid,
                    "window_id": window_id,
                    "include_screenshot": False,
                    "max_elements": 128,
                },
            )
            first_snapshot, field_token, button_token = _oracles.validate_cua_window_state(
                first,
                expected_pid=pid,
                window_id=window_id,
                diagnostic_phase=markers,
            )
        except ValueError:
            _portable_phase(phase, markers, "cua-snapshot")
            raise
        _mark(phase, "click-field")
        _oracles.validate_cua_action(
            await client.call(
                "relay_cua_click",
                {"pid": pid, "window_id": window_id, "element_token": field_token},
            ),
            tool_name="relay_cua_click",
        )
        _mark(phase, "type-field")
        _oracles.validate_cua_action(
            await client.call(
                "relay_cua_type_text",
                {
                    "pid": pid,
                    "window_id": window_id,
                    "element_token": field_token,
                    "text": value,
                },
            ),
            tool_name="relay_cua_type_text",
        )
        _mark(phase, "recapture")
        second = await client.call(
            "relay_cua_get_window_state",
            {
                "pid": pid,
                "window_id": window_id,
                "include_screenshot": False,
                "max_elements": 128,
            },
        )
        second_snapshot, _, fresh_button_token = _oracles.validate_cua_window_state(
            second,
            expected_pid=pid,
            window_id=window_id,
        )
        if second_snapshot == first_snapshot or fresh_button_token == button_token:
            raise ValueError("CUA snapshot token was not refreshed")
        _mark(phase, "stale-click")
        stale = await client.call(
            "relay_cua_click",
            {"pid": pid, "window_id": window_id, "element_token": button_token},
        )
        if stale.isError is not True or button_token in str(stale):
            raise ValueError("stale CUA element was not safely rejected")
        _mark(phase, "stale-click-oracle")
        _oracles.assert_no_fixture_event(artifact)
        _mark(phase, "click-button")
        _oracles.validate_cua_action(
            await client.call(
                "relay_cua_click",
                {"pid": pid, "window_id": window_id, "element_token": fresh_button_token},
            ),
            tool_name="relay_cua_click",
        )
    _mark(phase, "artifact-event")
    deadline = time.monotonic() + EVENT_POLL_TIMEOUT
    previous: bytes | None = None
    while time.monotonic() < deadline:
        try:
            current = _oracles.validate_cua_event(
                artifact,
                run_id=runtime.run_id,
                value=value,
            )
        except ValueError:
            time.sleep(0.05)
            continue
        if current == previous:
            _mark(phase, "stable-event")
            return
        previous = current
        time.sleep(0.1)
    _oracles.validate_cua_event(
        artifact,
        run_id=runtime.run_id,
        value=value,
    )


def run_cua_scenario(
    runtime: RuntimeConfig,
    value: str,
    phase: list[str] | None = None,
    *,
    expected_capabilities: tuple[str, ...] | None = None,
    expected_cua_app: str,
    expected_cua_window_title: str,
) -> None:
    """Run the shared generic CUA scenario with bounded cleanup."""
    asyncio.run(
        asyncio.wait_for(
            _run_cua_scenario_async(
                runtime,
                value,
                phase,
                expected_capabilities,
                expected_cua_app=expected_cua_app,
                expected_cua_window_title=expected_cua_window_title,
            ),
            timeout=MCP_OPERATION_TIMEOUT * 8,
        )
    )
